config/routes.rb
Rails.application.routes.draw do
  get 'robots', to: 'welcome#robots', defaults: { format: 'txt' }

  root "candidate_battles#new"

  resource :candidate_battles, only: :new
  resource :candidates, only: :update
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/candidate.rb
class Candidate < ApplicationRecord
  scope :random, -> { order("RANDOM()").limit(1).first }
  scope :not_id, ->(id) { where.not(id: id) }
  scope :special, ->(special) { where(special: special) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/candidate_battles_controller.rb
class CandidateBattlesController < ApplicationController
  def new
    @player_a = Candidate.random
    @player_b = Candidate.not_id(@player_a.id).special(@player_a.special).random
  end
end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController
  before_action :fetch_winner
  before_action :fetch_loser

  def update
    CalculatePlayersRatingService.new(winner: @winner, loser: @loser).call

    redirect_to new_candidate_battles_path
  rescue StandardError
    redirect_to new_candidate_battles_path, notice: "Algo de errado aconteceu, por favor, tente novamente!"
  end

  private

  def fetch_winner
    @winner = Candidate.find(params[:winner])
  end

  def fetch_loser
    @loser = Candidate.find(params[:loser])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/candidate_battles/_candidate.html.erb
<%= link_to candidates_path(winner: winner, loser: loser), data: { turbo_method: :put }, class: 'text-decoration-none text-reset' do %>
  <span>
    <img class="<%= candidate.avatar %>" alt="" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAKEAAADhAQMAAACax0eZAAAAA1BMVEX///+nxBvIAAAAAXRSTlMAQObYZgAAABxJREFUeNrtwTEBAAAAwqD1T20Gf6AAAAAAgM8AE1YAARzmcjEAAAAASUVORK5CYII=">
    <p><small><%= candidate.name %></small></p>
  </span>
<% end %>

app/views/candidate_battles/new.html.erb
<div class="row mt-5 text-center">
  <h3>Quem fará mais votos? Clique para escolher.</h3>
</div>

<div class="d-flex justify-content-center">
  <div class="row mt-4 text-center">
    <div class="col">
      <%= render 'candidate', candidate: @player_a, winner: @player_a, loser: @player_b %>
    </div>

    <div class="col-2 align-self-center">
      <h3>OU</h3>
    </div>

    <div class="col">
      <%= render 'candidate', candidate: @player_b, winner: @player_b, loser: @player_a %>
    </div>
  </div>
</div>

<div class="row mt-5 text-center small">
  <small>Foi utilizado um método estatístico chamado <%= link_to 'Elo Rating System', 'https://en.wikipedia.org/wiki/Elo_rating_system', target: '_blank' %>.</small>
  <small>Feito apenas para fins de pesquisa e entretenimento.</small>
  <small><strong>2024</strong></small>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "IBIMASH" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <!-- Google tag (gtag.js) -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-X8K869ZMJH"></script>
    <script>
     window.dataLayer = window.dataLayer || [];
     function gtag(){dataLayer.push(arguments);}
     gtag('js', new Date());

     gtag('config', 'G-X8K869ZMJH');
    </script>
  </head>

  <body>
    <div class="row p-1 pt-2 bg-primary text-center">
      <h2 class="text-white">IBIMASH</h2>
    </div>
    <div class="container">
      <% if flash[:notice] %>
	<div class="alert mt-5 text-center alert-danger" role="alert">
	  <%= flash[:notice] %>
	</div>
      <% end  %>

      <%= yield %>
    </div>
  </body>
</html>